# Generated by Django 5.2.7 on 2025-11-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mcreations', '0002_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='password',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
