# Generated by Django 5.2.7 on 2025-11-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mcreations', '0003_userregister_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='pincode',
        ),
    ]
